[package]
name = "c--"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
pest = { version = "2.8.3", features = ["pretty-print"] }
pest_derive = { version = "2.8.3", features = ["grammar-extras"] }
